### ISSUE TITLE
A better ICMP library

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#49]
Hello,

I just notice that in #47 the `lib/icmp` and `icmp_scan` need to run as root to be working, I glad if someone can give us a better solution and contribute a new lib and replace the libraries.

let me know if anyone has any idea.

Best Regards.

**Comment by shaddygarg** [comment]
Hey @Ali-Razmjoo, 
I read about the issue of running icmp scan as root but I can't seem to find a possible solution. This is because we need to create a raw socket while sending a icmp packet and linux doesn't allow creation of raw sockets without root privileges. Alternatively we can use the ping command to run in the background using os.system('ping host'). But it won't serve the same purpose as that of a full fledged icmp library. So, I think we should implement it in the following way.
1. Check if the user logged in has root privileges
2. If it has root permissions, use the existing library to perform the task
3. Otherwise we can resort to os.system('ping host')

Regards.

**Comment by shaddygarg** [comment]
I would like to know your views on the above implementation.

**Comment by Ali-Razmjoo** [comment]
Hello,

Please let me research on this topic, I will get back to you soon, thank you for sharing your solution.

Regards.

**Comment by pallav12** [comment]
Hello, 
icmp_scannning is just a way to know if target is active, we can do this with simple ping like this
``
import os

hostname = "google.com" #example

response = os.system("ping -c 1 " + hostname)
if response == 0:

  print hostname, 'is up!'

else:

  print hostname, 'is down!'

``
am I missing something?

**Comment by Ali-Razmjoo** [comment]
it gets extra time to do that, I think we are going to focus on docker image instead to avoid such issues.

**Comment by securestep9** [comment]
@pallav12  the whole idea of Nettacker is to be 100% in python and not dependent on other tools installed in OS like nmap/ping etc-  calling an OS command is not scaleable in terms of pythons multi-threading. Most people run nettacker in Kali Linux as root anyway and can also use it in docker as @Ali-Razmjoo has already mentioned.

**Comment by pallav12** [comment]
Ohh okay, makes sense

**Comment by abinpaul1** [comment]
[icmplib](https://github.com/ValentinBELYN/icmplib) is a new library which provides a pure Python implementation of the ICMP protocol along with the option of running as non-root.

**Comment by Ali-Razmjoo** [comment]
@abinpaul1 👍 

yeah we will add this as dependecy https://pypi.org/project/icmplib/

**Comment by abinpaul1** [comment]
@Ali-Razmjoo I would be happy to work on this. However the library is only compatible with python 3.6+. 
So I think I could go about it in two ways
- Keep the current implementation and use the new library if python version is more than 3.6
- Replace the current implmentation
Do let me know, I would be happy to open a pull request for the same

**Comment by Ali-Razmjoo** [comment]
done in #440

**Comment by abinpaul1** [comment]
Hi
I could see a lot of changes made in the PR,
However it seems the ICMP implementation still requires root to run. Was the idea to use 'icmplib' (which provides an option to run ping as non root) dropped
