### ISSUE TITLE
module http_ntlm_brute is not available

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#73]
Hello,

check the latest test on [TravisCI](https://travis-ci.org/viraintel/OWASP-Nettacker), this module having some errors.
```
[+] start attacking 127.0.0.1, 14 of 29
[X] this module "http_ntlm_brute" is not available
[!] unable to open http://127.0.0.1/
[+] start attacking 127.0.0.1, 16 of 29
[+] start attacking 127.0.0.1, 18 of 29
[+] start attacking 127.0.0.1, 17 of 29
[X] this module "http_form_brute" is not available
[+] start attacking 127.0.0.1, 19 of 29
[+] trying 1 of 16 in process 3 of 29 127.0.0.1:21 (telnet_brute)
```
Regards.
_________________
**OS**: `Linux`

**OS Version**: `using TravisCI`

**Python Version**: `2.x`, `3.x`

**Comment by shaddygarg** [comment]
Hey,
I will have a look into it and send a fix soon. 
Regards.

**Comment by JeckyOH** [comment]
@Ali-Razmjoo 
The reason of this issue is the ImportError of pycurl module in lib.brute.http_ntlm.py.
The error looks like this: 
`ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)`
It is apparent that pycurl is compiled without specifying the backend as openssl.
Here is the solution: [Solution of different backend of PyCurl between link time and compile time](http://pycurl.io/docs/latest/install.html).
I have tried to use this method on Linux Ubuntu and it can solve this issue. However, in Mac OS 10.13, it failed.
Because this is the error of compiling PyCurl, which is installed through requirements.txt and I`m afraid of disrupting the structure of the project, I cannot provide a PR to solve this problem.

**Comment by Ali-Razmjoo** [comment]
Hey @JeckyOH, 

Thanks for the details, I'm getting an error too and should be review and fix soon.

Regards.

______________
tested on 
* `python 2.7.13` windows 10
* `python 3.4.5` CentOS 6.5 
* `python 2.7.12` Ubuntu 16
