### ISSUE TITLE
[X] pip3 install -r requirements.txt ---> py3DNS==4.0.0 not installed!

### ISSUE THREAD

**Issue by whoami-hua** [OWASP/Nettacker#763]
Please describe the issue or question and share your OS and Python version.
_________________
**OS**: `x`

**OS Version**: `ventura 13.4`

**Python Version**: `3.10.9`

**Comment by whoami-hua** [comment]
macos

**Comment by Captain-T2004** [comment]
@securestep9 kindly assign me this issue. I will try to recreate this and find the solution.

**Comment by securestep9** [comment]
> @securestep9 kindly assign me this issue. I will try to recreate this and find the solution.

Sure - also check out #550

**Comment by Captain-T2004** [comment]
I haven't been able to recreate this issue on any PC i have tried. The library py3DNS (library_name = DNS) is actually not being used anywhere in the program as far as I can see, I believe that is why in the issue #550 changing the library_name from DNS to dns worked because it is imported from pythondns library instead of py3DNS. 
You can still try to install the dependency manually using the command : 
```
pip install py3dns 
or
python3 -m pip install py3dns
```
 I believe that should fix the issue.
