### ISSUE TITLE
join multiple vulnerability scanner

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#97]
Hello,

I notice we added multiple modules to check the HTTP headers for misconfiguration/vulnerabilities  (e.g. xss protection, content type, etc.. ). It's best to join them into one module and keep the vulnerability information in a JSON and we can name it `header_based_vuln?`.

I glad if someone could work on this.

Regards.

**Comment by pradeepjairamani** [comment]
how about making a directory structure for different vulnerabilities rather than having to combine all those vulnerabilities in one module as in if another developer wants to create a vulnerability for eg. header_based_vuln he will have to understand the entire data present in that module and editing those previously stable modules can cause instability and confusion.

Best Regards

**Comment by Ali-Razmjoo** [comment]
Hey @pradeepjairamani,

 I am not sure I quite understand you, could you please explain more?

Regards.

**Comment by pradeepjairamani** [comment]
So, you are asking to combine multiple modules into one single module which means a single engine.py for all the http header based vulnerabilities?
Doing that might create confusion for new developers and also can make the vulnerabilities unstable with each vulnerability being added. Better we should make folder structure like we discussed in cms scanner.
http_header_vuln > options_method >engine.py
http_header_vuln > XSS_protection  >engine.py
http_header_vuln > clickjacking >engine.py , etc

Best Regards

**Comment by Ali-Razmjoo** [comment]
I get it! Until http_header_vuln > engine.py be exist,  it's not a problem!

**Comment by pradeepjairamani** [comment]
Meaning?

**Comment by Ali-Razmjoo** [comment]
I meant we can combine modules just like you suggested. every module in a category could be in a subdirectory as a class.
